export const listItemStyle = {
  itemContainer: {
    flex: 1,
    borderRadius: 22,
    borderColor: 'white',
    borderWidth: 4,
    borderBottomWidth: 5,
    shadowColor: 'black',
    shadowOffset: {width: 0, height: 3},
    shadowOpacity: 1,
    shadowRadius: 3,
    marginBottom: 8,
  },
  item: {
    flex: 1,
    height: 62,
    borderRadius: 22,
    backgroundColor: '#fff6d8',
    shadowColor: '#edbc78',
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 1,
    shadowRadius: 0,
  },
  button: {
    position: 'absolute',
    // left: 0,
    width: '100%',
    height: '100%',
    justifyContent: 'center',
    // backgroundColor: 'rgba(0,255,0,0.3)',
    overflow: 'hidden',
  },
  content: {
    // flex: 1,
    width: '100%',
    // height: '100%',
    paddingVertical: 5,
    paddingLeft: 16,
    paddingRight: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    // backgroundColor: 'rgba(0,0,255,0.3)',
  },
  leftInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    // backgroundColor: 'rgba(0,0,255,0.3)',
  },
  rightInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    // backgroundColor: 'rgba(0,0,255,0.3)',
  },
  info: {
    marginLeft: 15,
    justifyContent: 'space-around',
    maxWidth: '70%',
  },
}